server:
  port: 8787
  context-path: /arlo

management:
  security:
    enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/arlo

---

spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://arlo-mongo:27017/arlo